terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.80.0" # Provider version
    }
  }
  required_version = ">= 1.7.5"
}

# The provider block to configure Google Cloud
provider "google" {
  project = var.project_id
  region  = var.region
  zone    = var.zone
}

# Google Kubernetes Engine Cluster
resource "google_container_cluster" "rag_gke" {
  name                     = "${var.project_id}-gke-1"
  location                 = var.region
  remove_default_node_pool = true # Remove default node pool generated by GKE, using customize node pool below
  initial_node_count       = 1
  node_locations           = [var.zone]
}


resource "google_container_node_pool" "primary_preemptible_node" {
  # A node pool specifies a set of nodes (VM instances) in your GKE cluster.
  name       = "primary-node-pool"
  location   = var.region
  cluster    = google_container_cluster.rag_gke.name
  node_count = 1 # Specifies that the node pool will have 1 node initially

  node_config {
    preemptible  = false # Not prememptible (preemptible is cheaper but limit to 24 hours)
    machine_type = "e2-standard-4"
  }

}

