namespace: indexing

ingress: 
  host: 34.124.156.157.nip.io

deployment:
  name: indexing
  replicaCount: 2
  labels:
    appName: indexing
  container:
    name: i-p
    portNumber: 8005
    args: []
  image:
    name: duonghust1919/indexing
    version: 1.1.3
    imagePullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 300m
      memory: 10Gi

service:
  name: idx-svc
  type: LoadBalancer
  httpPort:
    enable: true
    port: 83
    targetPort: 8005

env:
  QDRANT_URL: http://qdrant.qdrant.svc.cluster.local:6333
  VECTORIZE_URL: http://emb-svc.emb.svc.cluster.local:81/batch_embedding